//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellAudio.Extensions.Apple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellAudio.Extensions.Apple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized BitRate value &apos;{0}&apos;. Specify a value between &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        internal static string AacSampleEncoderBadBitRate {
            get {
                return ResourceManager.GetString("AacSampleEncoderBadBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized ControlMode value &apos;{0}&apos; in conjunction with BitRate. Specify &apos;Constrained&apos;, &apos;Average&apos; or &apos;Constant&apos;. Default is &apos;Constrained&apos;.
        /// </summary>
        internal static string AacSampleEncoderBadBitRateControlMode {
            get {
                return ResourceManager.GetString("AacSampleEncoderBadBitRateControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Quality value &apos;{0}&apos;. Specify &apos;Low&apos;, &apos;Medium&apos;, or &apos;High&apos;. Default is &apos;High&apos;.
        /// </summary>
        internal static string AacSampleEncoderBadQuality {
            get {
                return ResourceManager.GetString("AacSampleEncoderBadQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ControlMode other than &apos;Variable&apos; must be used in conjunction with the BitRate setting.
        /// </summary>
        internal static string AacSampleEncoderBadQualityControlMode {
            get {
                return ResourceManager.GetString("AacSampleEncoderBadQualityControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized VBRQuality value &apos;{0}&apos;. Specify a value between &apos;0&apos; (low) and &apos;14&apos; (high). Default is &apos;9&apos;.
        /// </summary>
        internal static string AacSampleEncoderBadVbrQuality {
            get {
                return ResourceManager.GetString("AacSampleEncoderBadVbrQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no sample filter named &apos;ReplayGain&apos; installed.
        /// </summary>
        internal static string AacSampleEncoderReplayGainFilterError {
            get {
                return ResourceManager.GetString("AacSampleEncoderReplayGainFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter Services encountered an error converting samples: {0}.
        /// </summary>
        internal static string LosslessSampleDecoderFillBufferError {
            get {
                return ResourceManager.GetString("LosslessSampleDecoderFillBufferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized flags value &apos;{0}&apos;.
        /// </summary>
        internal static string LosslessSampleDecoderFlagsError {
            get {
                return ResourceManager.GetString("LosslessSampleDecoderFlagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Apple Lossless file.
        /// </summary>
        internal static string LosslessSampleDecoderFormatError {
            get {
                return ResourceManager.GetString("LosslessSampleDecoderFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Services encountered an error while retrieving information about the magic cookie: {0}.
        /// </summary>
        internal static string LosslessSampleDecoderGetCookieInfoError {
            get {
                return ResourceManager.GetString("LosslessSampleDecoderGetCookieInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter Services encountered an error while setting the magic cookie: {0}.
        /// </summary>
        internal static string LosslessSampleDecoderSetCookieError {
            get {
                return ResourceManager.GetString("LosslessSampleDecoderSetCookieError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Lossless does not support {0} bits per second input.
        /// </summary>
        internal static string LosslessSampleEncoderBitRateError {
            get {
                return ResourceManager.GetString("LosslessSampleEncoderBitRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter Services encountered an error while initializing the converter: {0}.
        /// </summary>
        internal static string NativeAudioConverterInitializationError {
            get {
                return ResourceManager.GetString("NativeAudioConverterInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Services encountered an error while reading packets: {0}.
        /// </summary>
        internal static string NativeAudioConverterReadError {
            get {
                return ResourceManager.GetString("NativeAudioConverterReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File Services encountered an error while initializing the audio file: {0}.
        /// </summary>
        internal static string NativeAudioFileInitializationError {
            get {
                return ResourceManager.GetString("NativeAudioFileInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Audio File Services encountered an error while initializing the audio file: {0}.
        /// </summary>
        internal static string NativeExtendedAudioFileInitializationError {
            get {
                return ResourceManager.GetString("NativeExtendedAudioFileInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Application Support ({0}-bit), a component of iTunes, is not installed.
        /// </summary>
        internal static string SafeNativeMethodsDllsMissing {
            get {
                return ResourceManager.GetString("SafeNativeMethodsDllsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter Services encountered an error while setting the bit rate: {0}.
        /// </summary>
        internal static string SampleEncoderConverterBitRateError {
            get {
                return ResourceManager.GetString("SampleEncoderConverterBitRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter Services encountered an error while setting the control mode: {0}.
        /// </summary>
        internal static string SampleEncoderConverterControlModeError {
            get {
                return ResourceManager.GetString("SampleEncoderConverterControlModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Audio File Services encountered an error while saving the converter configuration: {0}.
        /// </summary>
        internal static string SampleEncoderConverterError {
            get {
                return ResourceManager.GetString("SampleEncoderConverterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Converter Services encountered an error while setting the quality: {0}.
        /// </summary>
        internal static string SampleEncoderConverterQualityError {
            get {
                return ResourceManager.GetString("SampleEncoderConverterQualityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Core Audio Toolbox {0}.
        /// </summary>
        internal static string SampleEncoderDescription {
            get {
                return ResourceManager.GetString("SampleEncoderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Audio File Services encountered an error while initializing the audio file: {0}.
        /// </summary>
        internal static string SampleEncoderInitializationError {
            get {
                return ResourceManager.GetString("SampleEncoderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no metadata encoder for the &apos;{0}&apos; extension installed.
        /// </summary>
        internal static string SampleEncoderMetadataEncoderError {
            get {
                return ResourceManager.GetString("SampleEncoderMetadataEncoderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Audio File Services encountered an error while writing a packet: {0}.
        /// </summary>
        internal static string SampleEncoderWriteError {
            get {
                return ResourceManager.GetString("SampleEncoderWriteError", resourceCulture);
            }
        }
    }
}
