//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellAudio.Extensions.Flac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellAudio.Extensions.Flac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered a decoding error. Status: {0}.
        /// </summary>
        internal static string AudioInfoDecoderDecodingError {
            get {
                return ResourceManager.GetString("AudioInfoDecoderDecodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error initializing the stream decoder: {0}.
        /// </summary>
        internal static string AudioInfoDecoderInitializationError {
            get {
                return ResourceManager.GetString("AudioInfoDecoderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an unsupported container.
        /// </summary>
        internal static string AudioInfoDecoderUnsupportedContainerError {
            get {
                return ResourceManager.GetString("AudioInfoDecoderUnsupportedContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered a decoding error. Status: {0}.
        /// </summary>
        internal static string MetadataDecoderDecodingError {
            get {
                return ResourceManager.GetString("MetadataDecoderDecodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error initializing the stream decoder: {0}.
        /// </summary>
        internal static string MetadataDecoderInitializationError {
            get {
                return ResourceManager.GetString("MetadataDecoderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an unsupported container.
        /// </summary>
        internal static string MetadataDecoderUnsupportedContainerError {
            get {
                return ResourceManager.GetString("MetadataDecoderUnsupportedContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized UsePadding value &apos;{0}&apos;. Specify &apos;True&apos; or &apos;False&apos;. Default is &apos;False&apos;.
        /// </summary>
        internal static string MetadataEncoderBadUsePadding {
            get {
                return ResourceManager.GetString("MetadataEncoderBadUsePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error attempting to delete a Vorbis Comment block.
        /// </summary>
        internal static string MetadataEncoderDeleteError {
            get {
                return ResourceManager.GetString("MetadataEncoderDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC was unable to allocate memory for a new metadata block.
        /// </summary>
        internal static string MetadataEncoderInsertBlockError {
            get {
                return ResourceManager.GetString("MetadataEncoderInsertBlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a FLAC file.
        /// </summary>
        internal static string MetadataEncoderNotFlacError {
            get {
                return ResourceManager.GetString("MetadataEncoderNotFlacError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error retrieving metadata: {0}.
        /// </summary>
        internal static string MetadataEncoderReadError {
            get {
                return ResourceManager.GetString("MetadataEncoderReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error while writing the temporary file. Status: {0}.
        /// </summary>
        internal static string MetadataEncoderTempFileError {
            get {
                return ResourceManager.GetString("MetadataEncoderTempFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error while writing the Vorbis comment block. Status: {0}.
        /// </summary>
        internal static string MetadataEncoderWriteError {
            get {
                return ResourceManager.GetString("MetadataEncoderWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error while allocating memory for a seek table.
        /// </summary>
        internal static string NativeSeekTableBlockMemoryError {
            get {
                return ResourceManager.GetString("NativeSeekTableBlockMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error while allocating memory for a vorbis comment.
        /// </summary>
        internal static string NativeVorbisCommentBlockMemoryError {
            get {
                return ResourceManager.GetString("NativeVorbisCommentBlockMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered a decoding error. Status: {0}.
        /// </summary>
        internal static string SampleDecoderDecodingError {
            get {
                return ResourceManager.GetString("SampleDecoderDecodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error initializing the stream decoder: {0}.
        /// </summary>
        internal static string SampleDecoderInitializationError {
            get {
                return ResourceManager.GetString("SampleDecoderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an unsupported container.
        /// </summary>
        internal static string SampleDecoderUnsupportedContainerError {
            get {
                return ResourceManager.GetString("SampleDecoderUnsupportedContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized AddMetadata value &apos;{0}&apos;. Specify &apos;True&apos; or &apos;False&apos;. Default is &apos;True&apos;.
        /// </summary>
        internal static string SampleEncoderBadAddMetadata {
            get {
                return ResourceManager.GetString("SampleEncoderBadAddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized CompressionLevel value &apos;{0}&apos;. Specify a value between &apos;0&apos; (fastest) and &apos;8&apos; (best). Default is &apos;5&apos;.
        /// </summary>
        internal static string SampleEncoderBadCompressionLevel {
            get {
                return ResourceManager.GetString("SampleEncoderBadCompressionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized SeekPointInterval value &apos;{0}&apos;. Specify a value greater than or equal to &apos;0&apos;. Default is &apos;10&apos;.
        /// </summary>
        internal static string SampleEncoderBadSeekPointInterval {
            get {
                return ResourceManager.GetString("SampleEncoderBadSeekPointInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Lossless Audio Codec ({0}).
        /// </summary>
        internal static string SampleEncoderDescription {
            get {
                return ResourceManager.GetString("SampleEncoderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an encoding error. Status: {0}.
        /// </summary>
        internal static string SampleEncoderEncodingError {
            get {
                return ResourceManager.GetString("SampleEncoderEncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC encountered an error initializing the encoder: {0}.
        /// </summary>
        internal static string SampleEncoderInitializationError {
            get {
                return ResourceManager.GetString("SampleEncoderInitializationError", resourceCulture);
            }
        }
    }
}
