//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellAudio.Extensions.Id3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellAudio.Extensions.Id3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized ID3Version value &apos;{0}&apos;. Specify &apos;2.2&apos;, &apos;2.3&apos; or &apos;2.4&apos;. Default is &apos;2.3&apos;.
        /// </summary>
        internal static string MetadataEncoderBadID3Version {
            get {
                return ResourceManager.GetString("MetadataEncoderBadID3Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized PaddingSize value &apos;{0}&apos;. Specify a value between &apos;0&apos; and &apos;268435456&apos; bytes. Default is &apos;0&apos;.
        /// </summary>
        internal static string MetadataEncoderBadPaddingSize {
            get {
                return ResourceManager.GetString("MetadataEncoderBadPaddingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized UsePadding value &apos;{0}&apos;. Specify &apos;True&apos; or &apos;False&apos;. Default is &apos;False&apos;.
        /// </summary>
        internal static string MetadataEncoderBadUsePadding {
            get {
                return ResourceManager.GetString("MetadataEncoderBadUsePadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized AddSoundCheck value &apos;{0}&apos;. Specify &apos;Album&apos;, &apos;Track&apos; or &apos;False&apos;. Default is &apos;False&apos;.
        /// </summary>
        internal static string MetadataToTagModelAdapterBadAddSoundCheck {
            get {
                return ResourceManager.GetString("MetadataToTagModelAdapterBadAddSoundCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain an AlbumGain value.
        /// </summary>
        internal static string MetadataToTagModelAdapterMissingAlbumGain {
            get {
                return ResourceManager.GetString("MetadataToTagModelAdapterMissingAlbumGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain an AlbumPeak value.
        /// </summary>
        internal static string MetadataToTagModelAdapterMissingAlbumPeak {
            get {
                return ResourceManager.GetString("MetadataToTagModelAdapterMissingAlbumPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain a TrackGain value.
        /// </summary>
        internal static string MetadataToTagModelAdapterMissingTrackGain {
            get {
                return ResourceManager.GetString("MetadataToTagModelAdapterMissingTrackGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain a TrackPeak value.
        /// </summary>
        internal static string MetadataToTagModelAdapterMissingTrackPeak {
            get {
                return ResourceManager.GetString("MetadataToTagModelAdapterMissingTrackPeak", resourceCulture);
            }
        }
    }
}
