//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellAudio.Extensions.Mp4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellAudio.Extensions.Mp4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DCD descriptor.
        /// </summary>
        internal static string EsdsAtomDcdError {
            get {
                return ResourceManager.GetString("EsdsAtomDcdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DSI descriptor.
        /// </summary>
        internal static string EsdsAtomDsiError {
            get {
                return ResourceManager.GetString("EsdsAtomDsiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object type is not supported.
        /// </summary>
        internal static string EsdsAtomTypeError {
            get {
                return ResourceManager.GetString("EsdsAtomTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized AddMetadata value &apos;{0}&apos;. Specify &apos;True&apos; or &apos;False&apos;. Default is &apos;True&apos;.
        /// </summary>
        internal static string MetadataEncoderBadAddMetadata {
            get {
                return ResourceManager.GetString("MetadataEncoderBadAddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the specified creation time: {0}.
        /// </summary>
        internal static string MetadataEncoderBadCreationTime {
            get {
                return ResourceManager.GetString("MetadataEncoderBadCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized AddSoundCheck value &apos;{0}&apos;. Specify &apos;Album&apos;, &apos;Track&apos; or &apos;False&apos;. Default is &apos;False&apos;.
        /// </summary>
        internal static string MetadataToAtomAdapterBadAddSoundCheck {
            get {
                return ResourceManager.GetString("MetadataToAtomAdapterBadAddSoundCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain an AlbumGain value.
        /// </summary>
        internal static string MetadataToAtomAdapterMissingAlbumGain {
            get {
                return ResourceManager.GetString("MetadataToAtomAdapterMissingAlbumGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain an AlbumPeak value.
        /// </summary>
        internal static string MetadataToAtomAdapterMissingAlbumPeak {
            get {
                return ResourceManager.GetString("MetadataToAtomAdapterMissingAlbumPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain a TrackGain value.
        /// </summary>
        internal static string MetadataToAtomAdapterMissingTrackGain {
            get {
                return ResourceManager.GetString("MetadataToAtomAdapterMissingTrackGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata does not contain a TrackPeak value.
        /// </summary>
        internal static string MetadataToAtomAdapterMissingTrackPeak {
            get {
                return ResourceManager.GetString("MetadataToAtomAdapterMissingTrackPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while traversing the atom structure.
        /// </summary>
        internal static string Mp4AtomNotFoundError {
            get {
                return ResourceManager.GetString("Mp4AtomNotFoundError", resourceCulture);
            }
        }
    }
}
