//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellAudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellAudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; bits per sample is not supported.
        /// </summary>
        internal static string AudioInfoBitsPerSampleIsOutOfRangeError {
            get {
                return ResourceManager.GetString("AudioInfoBitsPerSampleIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported channel count.
        /// </summary>
        internal static string AudioInfoChannelsOutOfRangeError {
            get {
                return ResourceManager.GetString("AudioInfoChannelsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format is null or empty.
        /// </summary>
        internal static string AudioInfoFormatIsEmptyError {
            get {
                return ResourceManager.GetString("AudioInfoFormatIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid sample count.
        /// </summary>
        internal static string AudioInfoSampleCountIsOutOfRangeError {
            get {
                return ResourceManager.GetString("AudioInfoSampleCountIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported sample rate.
        /// </summary>
        internal static string AudioInfoSampleRateIsOutOfRangeError {
            get {
                return ResourceManager.GetString("AudioInfoSampleRateIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid maximum width.
        /// </summary>
        internal static string ConvertibleCoverArtConvertMaxWidthOutOfRangeError {
            get {
                return ResourceManager.GetString("ConvertibleCoverArtConvertMaxWidthOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid quality index.
        /// </summary>
        internal static string ConvertibleCoverArtConvertQualityOutOfRangeError {
            get {
                return ResourceManager.GetString("ConvertibleCoverArtConvertQualityOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data array is empty.
        /// </summary>
        internal static string CoverArtDataIsEmptyError {
            get {
                return ResourceManager.GetString("CoverArtDataIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is null or empty.
        /// </summary>
        internal static string CoverArtExportFileNameIsEmptyError {
            get {
                return ResourceManager.GetString("CoverArtExportFileNameIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string CoverArtFileDoesNotExistError {
            get {
                return ResourceManager.GetString("CoverArtFileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists.
        /// </summary>
        internal static string CoverArtFileExistsError {
            get {
                return ResourceManager.GetString("CoverArtFileExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; contains no data.
        /// </summary>
        internal static string CoverArtFileIsEmptyError {
            get {
                return ResourceManager.GetString("CoverArtFileIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only bitmap, JPEG and PNG images are supported as cover art.
        /// </summary>
        internal static string CoverArtUnsupportedImageFormatError {
            get {
                return ResourceManager.GetString("CoverArtUnsupportedImageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count &apos;{0}&apos; must be 1 or greater.
        /// </summary>
        internal static string GroupTokenCountIsOutOfRangeError {
            get {
                return ResourceManager.GetString("GroupTokenCountIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid day of the month.
        /// </summary>
        internal static string MetadataDictionaryDayError {
            get {
                return ResourceManager.GetString("MetadataDictionaryDayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is null or empty.
        /// </summary>
        internal static string MetadataDictionaryItemKeyIsEmptyError {
            get {
                return ResourceManager.GetString("MetadataDictionaryItemKeyIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid month.
        /// </summary>
        internal static string MetadataDictionaryMonthError {
            get {
                return ResourceManager.GetString("MetadataDictionaryMonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid year.
        /// </summary>
        internal static string MetadataDictionaryYearError {
            get {
                return ResourceManager.GetString("MetadataDictionaryYearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel count &apos;{0}&apos; must be 1 or greater.
        /// </summary>
        internal static string SampleCollectionFactoryCreateChannelsIsOutOfRangeError {
            get {
                return ResourceManager.GetString("SampleCollectionFactoryCreateChannelsIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample count &apos;{0}&apos; must be 0 or greater.
        /// </summary>
        internal static string SampleCollectionFactoryCreateSampleCountIsOutOfRangeError {
            get {
                return ResourceManager.GetString("SampleCollectionFactoryCreateSampleCountIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample count &apos;{0}&apos; must be 1 or greater.
        /// </summary>
        internal static string SampleCollectionFactoryResizeSampleCountIsOutOfRangeError {
            get {
                return ResourceManager.GetString("SampleCollectionFactoryResizeSampleCountIsOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is null or empty.
        /// </summary>
        internal static string SettingsDictionaryKeyIsEmptyError {
            get {
                return ResourceManager.GetString("SettingsDictionaryKeyIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is null or empty.
        /// </summary>
        internal static string SettingsDictionaryValueIsEmptyError {
            get {
                return ResourceManager.GetString("SettingsDictionaryValueIsEmptyError", resourceCulture);
            }
        }
    }
}
