//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellAudio.Extensions.Vorbis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellAudio.Extensions.Vorbis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the ogg stream was unexpectedly reached.
        /// </summary>
        internal static string EndOfStreamError {
            get {
                return ResourceManager.GetString("EndOfStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while creating a new comment packet.
        /// </summary>
        internal static string MetadataEncoderHeaderOutError {
            get {
                return ResourceManager.GetString("MetadataEncoderHeaderOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogg encountered an error while initializing the Ogg stream.
        /// </summary>
        internal static string NativeOggStreamInitializationError {
            get {
                return ResourceManager.GetString("NativeOggStreamInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogg encountered an error while reading a packet.
        /// </summary>
        internal static string NativeOggStreamPacketInError {
            get {
                return ResourceManager.GetString("NativeOggStreamPacketInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogg encountered an error while reading a page.
        /// </summary>
        internal static string NativeOggStreamPageInError {
            get {
                return ResourceManager.GetString("NativeOggStreamPageInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogg encountered an error while initializing the Ogg sync.
        /// </summary>
        internal static string NativeOggSyncInitializationError {
            get {
                return ResourceManager.GetString("NativeOggSyncInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogg encountered an error while writing.
        /// </summary>
        internal static string NativeOggSyncWroteError {
            get {
                return ResourceManager.GetString("NativeOggSyncWroteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while reading the header: {0}.
        /// </summary>
        internal static string NativeVorbisDecoderHeaderInError {
            get {
                return ResourceManager.GetString("NativeVorbisDecoderHeaderInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Vorbis header packet.
        /// </summary>
        internal static string NativeVorbisDecoderNotVorbisError {
            get {
                return ResourceManager.GetString("NativeVorbisDecoderNotVorbisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while adding a block: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderAddBlockError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderAddBlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while analyzing a block: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderAnalysisError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderAnalysisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while initializing the DSP state.
        /// </summary>
        internal static string NativeVorbisEncoderAnalysisInitialize {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderAnalysisInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing a Vorbis block.
        /// </summary>
        internal static string NativeVorbisEncoderBlockInitialize {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderBlockInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while reading a block: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderBlockOutError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderBlockOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while controlling the encoder: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderControlError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while flushing a packet: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderFlushPacketError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderFlushPacketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while reading the header: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderHeaderOutError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderHeaderOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while initializing the encoder: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderInitializationError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while setting up the encoder: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderSetupError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis encountered an error while writing to the encoder: {0}.
        /// </summary>
        internal static string NativeVorbisEncoderWroteError {
            get {
                return ResourceManager.GetString("NativeVorbisEncoderWroteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the file was unexpectedly reached.
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized AddMetadata value &apos;{0}&apos;. Specify &apos;True&apos; or &apos;False&apos;. Default is &apos;True&apos;.
        /// </summary>
        internal static string SampleEncoderBadAddMetadata {
            get {
                return ResourceManager.GetString("SampleEncoderBadAddMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized BitRate value &apos;{0}&apos;. Specify a value between &apos;32&apos; and &apos;500&apos;.
        /// </summary>
        internal static string SampleEncoderBadBitRate {
            get {
                return ResourceManager.GetString("SampleEncoderBadBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized ControlMode value &apos;{0}&apos; in conjunction with BitRate. Specify &apos;Variable&apos;, &apos;Average&apos; or &apos;Constant&apos;. Default is &apos;Variable&apos;.
        /// </summary>
        internal static string SampleEncoderBadBitRateControlMode {
            get {
                return ResourceManager.GetString("SampleEncoderBadBitRateControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized ControlMode value &apos;{0}&apos; in conjunction with VBRQuality. Default is &apos;Variable&apos;.
        /// </summary>
        internal static string SampleEncoderBadQualityControlMode {
            get {
                return ResourceManager.GetString("SampleEncoderBadQualityControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized SerialNumber value &apos;{0}&apos;. Specify a non-negative integer value. Default is random.
        /// </summary>
        internal static string SampleEncoderBadSerialNumber {
            get {
                return ResourceManager.GetString("SampleEncoderBadSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized VBRQuality value &apos;{0}&apos;. Specify a value between &apos;-1&apos; (low) and &apos;10&apos; (high). Default is &apos;5&apos;.
        /// </summary>
        internal static string SampleEncoderBadVbrQuality {
            get {
                return ResourceManager.GetString("SampleEncoderBadVbrQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no sample filter named &apos;ReplayGain&apos; installed.
        /// </summary>
        internal static string SampleEncoderReplayGainFilterError {
            get {
                return ResourceManager.GetString("SampleEncoderReplayGainFilterError", resourceCulture);
            }
        }
    }
}
